// This file is auto-generated by Convex
// Run `npx convex dev` to regenerate it with your schema

/* eslint-disable @typescript-eslint/no-explicit-any */
export type QueryCtx = any;
export type MutationCtx = any;
export type ActionCtx = any;

// Stub functions - these will be replaced when you run `npx convex dev`
export function query<T>(config: { args: any; handler: any }): T {
  return config as T;
}

export function mutation<T>(config: { args: any; handler: any }): T {
  return config as T;
}

export function action<T>(config: { args: any; handler: any }): T {
  return config as T;
}

export function internalQuery<T>(config: { args: any; handler: any }): T {
  return config as T;
}

export function internalMutation<T>(config: { args: any; handler: any }): T {
  return config as T;
}

export function internalAction<T>(config: { args: any; handler: any }): T {
  return config as T;
}
